# Sucinta introducción a [Julia](http://julialang.org/)

En Julia (junto con el notebook) podemos manejar distintos tipos de datos, por ejemplo números enteros.

_Nb. Para ejecutar el contenido de una celda las formas más comunes de hacerlo son teclear `<shift> + <enter>` si se desea insertar una celda abajo, o `<control> + <enter>`, si se desea ejecutar sin insertar una celda abajo._

In [1]:
1

1

O números de punto flotante,

In [2]:
1.0

1.0

Al preguntarle a Julia el tipo de datos que son, nos dirá que `1` y `1.0` son de tipo **Int** y **Float**, el número que sigue después de esto está relacioado con la cantidad de bits que utiliza la computadora para representar dichos números.

In [3]:
typeof(1), typeof(1.0)

(Int64,Float64)

Si le preguntamos si el uno entero y el uno flotante tienen el mismo valor nos dirá que sí, como debe ser.

In [4]:
1 == 1.0

true

Si preguntamos si `0.0` y `-0.0` son iguales, nos dirá que sí,

In [5]:
0.0 == -0.0

true

pero al momento de preguntarle si ambos son idénticos no duda en decirnos que no.

In [6]:
0.0 === -0.0

false

La razón de esto la vemos claramente en las representaciones en bits de ambos números,

In [7]:
bits(0.0)

"0000000000000000000000000000000000000000000000000000000000000000"

In [8]:
bits(-0.0)

"1000000000000000000000000000000000000000000000000000000000000000"

además nos da una pista valiosa acerca de ese primer 1 en la representación en bits; es en efecto el bit de signo (el bit más significativo), podemos también ver que la función `bits()` nos regresó una cadena. Si indagamos en la longitud de la cadena veremos que es 64, que es justo el número de bits que usa nuestra computadora para representar estos números (cosa que ya esperábamos).

In [9]:
length(ans)

64

In [10]:
bits(-1.0)

"1011111111110000000000000000000000000000000000000000000000000000"

In [11]:
bits(1.0)

"0011111111110000000000000000000000000000000000000000000000000000"

In [13]:
bits(1.1)

"0011111111110001100110011001100110011001100110011001100110011010"

In [14]:
1.1

1.1

In [15]:
big(1.1)

1.100000000000000088817841970012523233890533447265625e+00 with 256 bits of precision

In [16]:
2.0^(-14)

6.103515625e-5

In [17]:
bits(ans)

"0011111100010000000000000000000000000000000000000000000000000000"

In [20]:
BigFloat("1.1")

1.100000000000000000000000000000000000000000000000000000000000000000000000000003e+00 with 256 bits of precision

In [22]:
bits(2.0)

"0100000000000000000000000000000000000000000000000000000000000000"

In [23]:
bits(1.0)

"0011111111110000000000000000000000000000000000000000000000000000"

In [24]:
typemax(1.0)

Inf

In [25]:
bits(ans)

"0111111111110000000000000000000000000000000000000000000000000000"

**Ejercicio 1**

Qué significa el exponente?

In [26]:
typemax(1)

9223372036854775807

In [27]:
typemax(1) + 1

-9223372036854775808

In [28]:
9223372036854775807.0 + 1

9.223372036854776e18

In [29]:
int128(9223372036854775807) + 1

9223372036854775808

In [30]:
typemax(Int128)

170141183460469231731687303715884105727

In [31]:
ans + 1

-170141183460469231731687303715884105728

In [32]:
BigInt(typemax(Int)) + 1

9223372036854775808

In [33]:
typeof(ans)

BigInt (constructor with 10 methods)

In [34]:
BigInt(1)//2

1//2

In [35]:
typeof(ans)

Rational{BigInt} (constructor with 1 method)

In [36]:
prevfloat(typemax(Float64))

1.7976931348623157e308

In [37]:
bits(ans)

"0111111111101111111111111111111111111111111111111111111111111111"

In [38]:
prevfloat(typemax(Float64)) + 0.1

1.7976931348623157e308

In [40]:
prevfloat(prevfloat(typemax(Float64)))

1.7976931348623155e308

**Ejercicio 2**

¿Cuál es el número más chico que sumado (o restado) a 1.0 me da algo distinto de 1.0?

(Este número se bautiza como el "épsilon de la máquina")

¿Cuál es el número más chico que sumado (o restado) a 10.0 me da algo distinto de 10.0?



In [41]:
1.0 + 1.0e-308

1.0

In [42]:
ans == 1.0

true

In [43]:
ϵ

LoadError: ϵ not defined
while loading In[43], in expression starting on line 1

In [44]:
x = 2.25

2.25

In [45]:
y = x

2.25

In [46]:
y = 0.1

0.1

In [47]:
x

2.25

In [52]:
x = [0.1, 2.3]

2-element Array{Float64,1}:
 0.1
 2.3

In [56]:
y = x

2-element Array{Float64,1}:
 -1.0
  2.1

In [57]:
y[1] = 3

3

In [58]:
x

2-element Array{Float64,1}:
 3.0
 2.1

In [59]:
x

2-element Array{Float64,1}:
 3.0
 2.1

In [60]:
typeof(x)

Array{Float64,1}

In [64]:
[1, 3, 2]

3-element Array{Int64,1}:
 1
 3
 2

In [65]:
typeof(ans)

Array{Int64,1}

In [66]:
sqrt(1.0)

1.0

In [67]:
typeof(ans)

Float64

In [68]:
sqrt(-1.0)

LoadError: DomainError
while loading In[68], in expression starting on line 1

In [69]:
x

2-element Array{Float64,1}:
 3.0
 2.1

In [70]:
x'

1x2 Array{Float64,2}:
 3.0  2.1

In [72]:
size(x')

(1,2)

In [73]:
size(x)

(2,)

In [78]:
[[1,2], [4,3]]

4-element Array{Int64,1}:
 1
 2
 4
 3

In [79]:
[[1,2] [4,3]]

2x2 Array{Int64,2}:
 1  4
 2  3

In [81]:
A = [1 2; 4 3]

2x2 Array{Int64,2}:
 1  2
 4  3

In [84]:
x' * A' * x

1-element Array{Float64,1}:
 60.03

In [85]:
y = [complex(1,1), complex(0,1)]

2-element Array{Complex{Int64},1}:
 1+1im
 0+1im

In [86]:
A * y

2-element Array{Complex{Int64},1}:
 1+3im
 4+7im

In [87]:
ans'

1x2 Array{Complex{Int64},2}:
 1-3im  4-7im

In [88]:
zeros(4)

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

In [89]:
ones(Int,4)

4-element Array{Int64,1}:
 1
 1
 1
 1

In [91]:
ones(2,3)

2x3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [92]:
for i in [3, 5, 1]
    println(i)
end

3
5
1


In [94]:
for i = 1:5
    println(i)
end

1
2
3
4
5


In [95]:
1:5

1:5

In [96]:
typeof(ans)

UnitRange{Int64} (constructor with 1 method)

In [97]:
collect(1:5)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [103]:
for i = 6:5
    println(i)
end

In [104]:
typeof(ans)

Nothing (constructor with 1 method)

In [105]:
6:5

6:5

In [106]:
typeof(ans)

UnitRange{Int64} (constructor with 1 method)

In [107]:
collect(6:5)

0-element Array{Int64,1}

In [108]:
i = 1
while i <= 5
    println(i)
    i += 1
end

1
2
3
4
5


In [112]:
for i = 1:100
    if i < 21
        println(i,"   ", factorial(i))
    else
        break
    end
end

1   1
2   2
3   6
4   24
5   120
6   720
7   5040
8   40320
9   362880
10   3628800
11   39916800
12   479001600
13   6227020800
14   87178291200
15   1307674368000
16   20922789888000
17   355687428096000
18   6402373705728000
19   121645100408832000
20   2432902008176640000


In [114]:
besselj0(3.2)

-0.32018816965712305

In [115]:
?besselj

INFO: Loading help data...


Base.besselj(nu, x)

   Bessel function of the first kind of order "nu", J_\nu(x).


In [116]:
besselj(3, 2.3)

0.17997893127753342

In [121]:
function f(x)
    2*x
end

f (generic function with 1 method)

In [122]:
f(1.2)

2.4

In [123]:
f(x) = 2*x

f (generic function with 1 method)

In [124]:
f(1.2)

2.4

In [125]:
misqrt(x) = sqrt(x)

misqrt (generic function with 1 method)

In [127]:
misqrt(-1.0)

LoadError: DomainError
while loading In[127], in expression starting on line 1

Lo siguiente es algo que uno **NUNCA**, pero **NUNCA**, debe hacer, ya que la función `misqrt` definida abajo **NO** es estable según el tipo: el resultado depende del valor y *no* del tipo.

In [129]:
function misqrt(x)
    if x >= 0.0
        return sqrt(x)
    else
        return sqrt(complex(x,0))
    end
end

misqrt (generic function with 1 method)

In [130]:
misqrt(1.0)

1.0

In [131]:
misqrt(-1.0)

0.0 + 1.0im

In [132]:
typeof(misqrt(1.0)), typeof(misqrt(-1.0))

(Float64,Complex{Float64})

In [133]:
g = x -> 2*x

(anonymous function)

In [134]:
g(1.2)

2.4

In [135]:
function v(x)
    println(x)
    return x
end

v (generic function with 1 method)

In [139]:
1 >= 8 < 10

false

In [141]:
v(1) <= v(8) < v(10)

8
1
10


true

In [142]:
v(1) <= v(-8) < v(10)

-8
1


false

In [147]:
(1 <= -8) & (-8 < 10)

false

In [150]:
v(v(1) <= v(-8)) & v(v(-8) < v(10))

1
-8
false
-8
10
true


false

In [146]:
(1 <= -8) | (-8 < 10)

true

In [148]:
(1 <= -8) && (-8 < 10)

false

In [151]:
v(v(1) <= v(-8)) && v(v(-8) < v(10))

1
-8
false


false

In [152]:
for i = 1:100
    i >= 21 && break
    println(i,"   ", factorial(i))
end

1   1
2   2
3   6
4   24
5   120
6   720
7   5040
8   40320
9   362880
10   3628800
11   39916800
12   479001600
13   6227020800
14   87178291200
15   1307674368000
16   20922789888000
17   355687428096000
18   6402373705728000
19   121645100408832000
20   2432902008176640000


In [153]:
v(v(1) <= v(8)) || v(v(8) < v(10))

1
8
true


true

In [154]:
1 <= 9

true

In [155]:
typeof(ans)

Bool

In [157]:
x

2-element Array{Float64,1}:
 3.0
 2.1

In [161]:
v(v(1) <= v(8)) || (xx = 3)

1
8
true


true

In [162]:
xx

LoadError: xx not defined
while loading In[162], in expression starting on line 1

Cadenas

In [167]:
a = "å esto es una cadena"

"å esto es una cadena"

In [168]:
a[1]

'å'

In [165]:
typeof(ans)

Char

In [169]:
typeof(a)

UTF8String (constructor with 2 methods)

In [175]:
bits(1.1)

"0011111111110001100110011001100110011001100110011001100110011010"

In [176]:
ans[1:1]

"0"

In [177]:
bits(1.1)

"0011111111110001100110011001100110011001100110011001100110011010"

In [178]:
ans[1]

'0'

In [179]:
bits(1.1)[2:13]

"011111111110"